"""initial_schema

Revision ID: 608d59366336
Revises: 
Create Date: 2026-02-20 20:05:37.706650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608d59366336'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('did', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('public_key_b64', sa.String(), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=False),
    sa.Column('is_claimed', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_index(op.f('ix_agents_did'), 'agents', ['did'], unique=False)
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.create_table('challenges',
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('requester_did', sa.String(), nullable=False),
    sa.Column('target_did', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_index(op.f('ix_challenges_nonce'), 'challenges', ['nonce'], unique=False)
    op.create_table('human_gates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('node_execution_id', sa.String(), nullable=False),
    sa.Column('workflow_run_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_to_review', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reviewer_did', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_gates_id'), 'human_gates', ['id'], unique=False)
    op.create_index(op.f('ix_human_gates_node_execution_id'), 'human_gates', ['node_execution_id'], unique=False)
    op.create_index(op.f('ix_human_gates_workflow_run_id'), 'human_gates', ['workflow_run_id'], unique=False)
    op.create_table('node_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_run_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('node_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('heuristic_passed', sa.Boolean(), nullable=True),
    sa.Column('heuristic_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_executions_id'), 'node_executions', ['id'], unique=False)
    op.create_index(op.f('ix_node_executions_workflow_run_id'), 'node_executions', ['workflow_run_id'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('gate_id', sa.String(), nullable=False),
    sa.Column('reviewer_did', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('commission_usd', sa.Float(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_gate_id'), 'review_tasks', ['gate_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_id'), 'review_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_review_tasks_reviewer_did'), 'review_tasks', ['reviewer_did'], unique=False)
    op.create_table('reviewers',
    sa.Column('did', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('specializations', sa.Text(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('tasks_approved_ratio', sa.Float(), nullable=True),
    sa.Column('total_earned', sa.Float(), nullable=True),
    sa.Column('stripe_account_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_index(op.f('ix_reviewers_did'), 'reviewers', ['did'], unique=False)
    op.create_index(op.f('ix_reviewers_user_id'), 'reviewers', ['user_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('input_schema', sa.Text(), nullable=True),
    sa.Column('output_schema', sa.Text(), nullable=True),
    sa.Column('heuristic_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_owner_id'), 'roles', ['owner_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_node_index', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_id'), 'workflow_runs', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('nodes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_owner_id'), 'workflows', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_owner_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_roles_owner_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_reviewers_user_id'), table_name='reviewers')
    op.drop_index(op.f('ix_reviewers_did'), table_name='reviewers')
    op.drop_table('reviewers')
    op.drop_index(op.f('ix_review_tasks_reviewer_did'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_gate_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_node_executions_workflow_run_id'), table_name='node_executions')
    op.drop_index(op.f('ix_node_executions_id'), table_name='node_executions')
    op.drop_table('node_executions')
    op.drop_index(op.f('ix_human_gates_workflow_run_id'), table_name='human_gates')
    op.drop_index(op.f('ix_human_gates_node_execution_id'), table_name='human_gates')
    op.drop_index(op.f('ix_human_gates_id'), table_name='human_gates')
    op.drop_table('human_gates')
    op.drop_index(op.f('ix_challenges_nonce'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_did'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
